# This will update the people.md page when the people.csv file updates
#
# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: people_updater

on:
  push:
    paths:
      - 'assets/people/pub_maker.py'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    env: # Or as an environment variable
      super_secret: ${{ secrets.SuperSecret }}
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install pandas
    - name: execute py script # run sj-gobierno.py to get the latest data
      run: python publications/pub_maker.py

    - name: commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Automatically updating the publcations pages" -a

    - name: push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: galah_production
