# Updating the publication lists
#
# This workflow runs a Python script that creates two pages on the website:
# science/galah_publications.md and science/external_publications.md
#
# This workflow will install Python dependencies, execute survey/pub_maker.py.
# It will then check if the publication pages have changed, and if so
# commit any changes.

name: Update Publications

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *' # Runs at 10 am AEST

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas matplotlib

    - name: execute pub_maker.py
      env:
        ADS_TOKEN: ${{ secrets.ADS_TOKEN }}
      run: python science/pub_maker.py

    - name: check for changes
    # The reason for this git diff check is that the SVG images created by
    # pub_maker.py change every run because matplotlib creates ID tags inside
    # the files with random values.
      run: |
        if git diff --exit-code science/galah_publications.md science/external_publications.md; then
          echo "No changes"
        else
          git config --local user.email "chow.meeker_0h@icloud.com"
          git config --local user.name "RobotGALAH"
          git add -A
          git commit -m "Automatically updating the publication files"
        fi
    - name: push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: galah_production
