# Updating the publication lists
#
# This workflow will install Python dependencies, execute survey/pub_maker.py, and commit any changes

name: Update Publications

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas matplotlib

    - name: execute pub_maker.py
      env:
        ADS_TOKEN: ${{ secrets.ADS_TOKEN }}
      run: python science/pub_maker.py

    - name: check for changes
      run: |
        if git diff --exit-code science/galah_publications.md science/external_publications.md; then
          echo "No changes"
        else
          git config --local user.email "robot@galahsurvey.org"
          git config --local user.name "Robot GALAH"
          git add -A
          git commit -m "Automatically updating the publication files"
        fi
    - name: push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: galah_production
