# Updating the publication lists
#
# This workflow will install Python dependencies, execute survey/pub_maker.py, and commit any changes

name: Update Publications

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: execute py script
      env:
        ADS_TOKEN: ${{ secrets.ADS_TOKEN }}
      run: python survey/pub_maker.py
    - name: commit files
      run: |
        git config --local user.email "robot@galahsurvey.org"
        git config --local user.name "Robot GALAH"
        git diff-index --quiet HEAD || (git commit -a -m "Automatically updating the publication files" && git push -f)
    - name: push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: galah_production
